#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BlaChat.Resource", IsApplication=true)]

namespace BlaChat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001f
			public const int action_defaultMessages = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int action_lessMessages = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int action_moreMessages = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int action_rename = 2131165216;
			
			// aapt resource value: 0x7f07001b
			public const int action_sendImage = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int action_setImage = 2131165217;
			
			// aapt resource value: 0x7f07001c
			public const int action_settings = 2131165212;
			
			// aapt resource value: 0x7f070008
			public const int chatImage = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int chatLayout = 2131165193;
			
			// aapt resource value: 0x7f070018
			public const int chatList = 2131165208;
			
			// aapt resource value: 0x7f07000d
			public const int chatMessage = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int chatName = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int chatRow = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int chatTime = 2131165196;
			
			// aapt resource value: 0x7f070015
			public const int contentImage = 2131165205;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout1 = 2131165194;
			
			// aapt resource value: 0x7f070013
			public const int linearLayout2 = 2131165203;
			
			// aapt resource value: 0x7f070006
			public const int login = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int message = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int messageCaption = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int messageImage = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public const int messageLayout = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int messageScrollView = 2131165198;
			
			// aapt resource value: 0x7f070019
			public const int messageText = 2131165209;
			
			// aapt resource value: 0x7f070003
			public const int password = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int passwordLabel = 2131165186;
			
			// aapt resource value: 0x7f070016
			public const int placeholder = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int scrollView1 = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int send = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int server = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int serverLabel = 2131165188;
			
			// aapt resource value: 0x7f07001a
			public const int timeInsertTime = 2131165210;
			
			// aapt resource value: 0x7f070001
			public const int username = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int usernameLabel = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Authentication = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Chat = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChatActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ImageLeft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ImageRight = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MessageLeft = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MessageRight = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TimeInsert = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int chat = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int data = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int profileUrl = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
