#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BlaChat.Resource", IsApplication=true)]

namespace BlaChat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int chatImage = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int chatLayout = 2131099659;
			
			// aapt resource value: 0x7f06001c
			public const int chatList = 2131099676;
			
			// aapt resource value: 0x7f06000d
			public const int chatMessage = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int chatName = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int chatRow = 2131099656;
			
			// aapt resource value: 0x7f060019
			public const int contentImage = 2131099673;
			
			// aapt resource value: 0x7f060010
			public const int defaultMessages = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int lessMessages = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int linearLayout1 = 2131099668;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout2 = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int login = 2131099655;
			
			// aapt resource value: 0x7f060015
			public const int message = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int messageCaption = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int messageImage = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int messageLayout = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int messageScrollView = 2131099666;
			
			// aapt resource value: 0x7f06001d
			public const int messageText = 2131099677;
			
			// aapt resource value: 0x7f06000f
			public const int moreMessages = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int password = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int passwordLabel = 2131099650;
			
			// aapt resource value: 0x7f06001a
			public const int placeholder = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int scrollView1 = 2131099675;
			
			// aapt resource value: 0x7f060016
			public const int send = 2131099670;
			
			// aapt resource value: 0x7f060006
			public const int server = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int serverLabel = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int space1 = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int space2 = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int username = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int usernameLabel = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Authentication = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Chat = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChatActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ImageLeft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ImageRight = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MessageLeft = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MessageRight = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int data = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int profileUrl = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
